#
# BungeeStaffList by Mackenzie Molloy
#
#   Discord - "Mackenzie Molloy#1821" / https://mackenziemolloy.net/discord
#

no-permission: "&cYou do not have permission."
config-reloaded: "&aConfiguration Reloaded."
staff-format: "{prefix} {username}&7 is currently on &b{server}"
stafflist-online:
  - ""
  - "&3&lStaff Online"
  - "&7{staff}"
  - ""
  - "&7Contact online staff with &f/helpop (message)&7."
  - ""

stafflist-none:
  - ""
  - "&cSorry, it looks like there is no staff online :("
  - ""

server-aliases:
  hub: "THE HUB"

# These group of messages is only applicable if you don't have a vanish plugin hook enabled.
staffhide:
  enabled-placeholder: "&c&o&nHIDDEN&7 from"
  disabled-placeholder: "&a&o&nREVEALED&7 on"
  toggle: "&7You have been {state}&7 the staff list."
  toggle-other: "&b{other}&7 is now {state}&7 the staff list."
  toggled-by-other: "&b{other}&7 forced you to be {state}&7 the staff list."

# This section is only applicable when no permissions plugin hook is enabled.
# To apply a user to a group, simply give the permission "stafflist.ranks.<rank-name>" (for example, mod would be "stafflist.ranks.mod")
# Note: The higher the weight, the higher up in the list the group will be.
ranks:
  mod:
    prefix: "&e[Mod]"
    weight: 5

notice-understood: false
