#
# BungeeStaffList by Mackenzie Molloy
#
#   Discord - "Mackenzie Molloy#1821" / https://mackenziemolloy.net/discord
#

no-permission: "&cYou do not have permission."
config-reloaded: "&aConfiguration Reloaded."
staff-format: "{prefix} {username}&7 is currently on &b{server}"
stafflist-online:
  - ""
  - "&3&lStaff Online"
  - "&7{staff}"
  - ""
  - "&7Contact online staff with &f/helpop (message)&7."
  - ""

stafflist-none:
  - ""
  - "&cSorry, it looks like there is no staff online :("
  - ""

server-aliases:
  hub: "THE HUB"

hooks:
  premiumvanish: false # To-do (make a /staffhide) -mackenzie
  luckperms: false

# This section is only applicable when no permissions plugin hook is enabled.
# To apply a user to a group, simply give the permission "stafflist.ranks.<rank-name>" (for example, mod would be "stafflist.ranks.mod")
# Note: The higher the weight, the higher up in the list the group will be.
ranks:
  mod:
    prefix: "&e[Mod]"
    weight: 5
